### ISSUE TITLE
cpanel-nDeploy-setup.sh returns Invalid TLS data in userdata file

### ISSUE THREAD

**Issue by henriqueccruz** [AnoopAlias/nDeploy#163]
Hi,

I'm enabling Xtendweb on a brand new server and this specific user doesn't get his config generated. Investigating the script, I found out that if the user config doesn't get generated in 600 secs, this error is returned.

Investigating further, last call is:
^CTraceback (most recent call last):
  File "/opt/nDeploy/scripts/generate_config.py", line 567, in <module>
    nginx_confgen(is_suspended, clusterenabled, *cluster_serverlist, configuser=cpaneluser, configdomain=the_sub_domain, maindomain=the_sub_domain)
  File "/opt/nDeploy/scripts/generate_config.py", line 258, in nginx_confgen
    time.sleep(1)

Any idea on how to solve it? This is a really important account. Thanks!

**Comment by henriqueccruz** [comment]
Nevermind, got it solved on my own.
Solution used:

1. Move the corrupt userdata directory to a new location.
`mv /var/cpanel/userdata /var/cpanel/userdata.orig`

2. Create a new userdata directory.
`mkdir /var/cpanel/userdata`

3. Run the userdata_update script to rebuild userdata files for all of your accounts.
`/usr/local/cpanel/bin/userdata_update --reset`

4. Run the fix_userdata_perms script to validate the userdata permissions settings.
`/usr/local/cpanel/bin/fix_userdata_perms`

5. Run the updateuserdatacache script to update the system's cache.
`/scripts/updateuserdatacache`

6. Rebuild Apache.
`/scripts/rebuildhttpdconf`

7. Restart Apache.
`/scripts/restartsrv_httpd`
