### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by maateen** [AnoopAlias/nDeploy#228]
When I run `/opt/nDeploy/scripts/cpanel-nDeploy-setup.sh enable` on my server, I get:

```python
Traceback (most recent call last):
  File "/opt/nDeploy/scripts/generate_config.py", line 706, in <module>
    nginx_confgen(is_suspended, myowner, clusterenabled, *cluster_serverlist, configuser=cpaneluser, configdomain=main_domain, maindomain=main_domain)  # Generate conf for main domain
  File "/opt/nDeploy/scripts/generate_config.py", line 519, in nginx_confgen
    app_template = templateEnv.get_template(apptemplate_code)
  File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 552, in get_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/lib64/python2.6/site-packages/jinja2/loaders.py", line 96, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib64/python2.6/site-packages/jinja2/loaders.py", line 143, in get_source
    pieces = split_template_path(template)
  File "/usr/lib64/python2.6/site-packages/jinja2/loaders.py", line 25, in split_template_path
    for piece in template.split('/'):
AttributeError: 'NoneType' object has no attribute 'split'
```
I think it's a bug, so reporting. Please let me know if anymore information is needed.

**Comment by maateen** [comment]
Fix: remove all files of V3 and then try to install v4.

**Comment by AnoopAlias** [comment]
Yes v3 and v4 are not compatible . You need to remove /etc/nginx and /opt/nDeploy also after removing v3 and before installing v4 .
